<?php 
    define("BEGIN_ETAPE_STAGIAIRE", 7);
    define("BEGIN_ETAPE_SUPERVISEUR", 4);
    define("MIN_NUMERO_DOSSIER", 100000);
    define("MAX_NUMERO_DOSSIER", 999999);
    define("LAST_ETAPE", 0);
    define("EN_ATTENTE_STAGIAIRE", "En attente stagiaire");
    define("EN_ATTENTE_SUPERVISEUR", "En attente superviseur");
    define("COMPLETE", "Complete");
    define("UTILISATEUR", "utilisateur");
    define("STAGIAIRE", "stagiaire");
    define("SUPERVISEUR", "superviseur");
    define("SUPERADMINISTRATEUR", "superadministrateur");
    define("ADMINISTRATEUR", "administrateur");
    define("FORMATION", "Formation");
    define("FORMATION_COMPLETE", "Formation complète");
    define("CONTENT_MARKETING", "Content Marketing");
    define("INBOUND_MARKETING", "Inbound Marketing");
    define("COMMUNITY_MANAGEMENT", "Community Management");
    define("E_MAILING", "E-mailing");
    define("INFOGRAPHIE", "Infographie");
    define("WEB_DESIGN", "Web Design");
    define("REFERENCEMENT", "Référencement");
    define("STAGE", "Stage");
    define("STAGE_ACADEMIQUE", "Stage Académique");
    define("STAGE_PRE_EMPLOI", "Stage Pré-Emploi");
    define("DEVELOPPEMENT_WEB", "Développement Web");
    define("INFOGRAPHIE_STAGE", "Infographie");
    define("PHOTOGRAPHIE", "Photographie");
    define("COMMUNITY_MANAGEMENT_STAGE", "Community Management");
    define("AUTHORIZED_EXTENSION_FILES_IMAGE", ["pdf", "jpg", "jpeg", "png", "gif", "webp"]);
    define("AUTHORIZED_EXTENSION_FILES_DOCUMENTS", ["pdf", "doc", "docx"]);
?>